name: Frontend CD

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Windows server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          timeout: 60s
          port: 22
          script: |
            cd C:\Users\jhlee\Desktop\soncoding-server
            call deploy.bat